parameters:
    youshido.graphql.processor.class: Youshido\GraphQLBundle\Processor\Processor

services:

    youshido.graphql.processor:
        class: %youshido.graphql.processor.class%
        calls:
            - [ setSchema, [@youshido.graphql.schema]]
            - [ setContainer, [@service_container]]
            - [ setLogger, [%youshido.graphql.logger%] ]


    youshido.graphql.schema:
        class: %youshido.graphql.project_schema%
