parameters:
    youshido.graphql.processor.class: Youshido\GraphQLBundle\Processor\Processor

services:

    youshido.graphql.processor:
        class: %youshido.graphql.processor.class%
        calls:
            - [ setContainer, ['@service_container']]
            - [ setLogger, [%youshido.graphql.logger%] ]
