parameters:
    youshido.graphql.processor.class: Youshido\GraphQLBundle\GraphQL\Processor

services:

    youshido.graphql.processor:
        class: %youshido.graphql.processor.class%
        calls:
            - [setQuerySchemaClass, [%youshido.graphql.project_schema%]]