parameters:
    youshido.graphql.processor.class: Youshido\GraphQLBundle\GraphQL\Processor

services:

    youshido.graphql.processor:
        class: %youshido.graphql.processor.class%
        arguments: [ @youshido.graphql.schema ]


    youshido.graphql.schema:
        class: %youshido.graphql.project_schema%