parameters:
    youshido.graphql.processor.class: Youshido\GraphQLBundle\Execution\Processor

services:

    youshido.graphql.processor:
        class: "%youshido.graphql.processor.class%"
        arguments: ["@youshido.graphql.schema"]
        calls:
            - [ setContainer, ["@service_container"]]
